name: Checkmarx CxOne Scan with SARIF Upload

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  security-events: write  # REQUIRED for SARIF uploads
  actions: read

jobs:
  checkmarx-scan:
    name: Run Checkmarx Scan + Upload SARIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Run Checkmarx Scan
        uses: checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://ast.checkmarx.net
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          project_name: ${{ github.event.repository.name }}
          branch: ${{ github.ref_name }}
          additional_params: --report-format sarif --output-path .

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
